In [4]:
# outer product and inner product

import numpy as np
v1=np.array([2,3,4,5,6])
v2=np.array([2,3,4,5,6])
v3=np.outer(v1,v2)
print(v3)
v4=np.dot(v1,v2)

print(v4)

[[ 4  6  8 10 12]
 [ 6  9 12 15 18]
 [ 8 12 16 20 24]
 [10 15 20 25 30]
 [12 18 24 30 36]]
90


In [6]:
#  hamdard product sign is circyle in middle dot ⚪
#  this should have same dimentions
import numpy as np
v1=np.array([1,2,3])
v2=np.array([4,5,6])
v3=v1*v2
print(v3)


[ 4 10 18]


In [ ]:
#  this is the unit vector first we should find norm
import numpy as np
v1=np.array([1,2,3,4,5])
vmag=np.linalg.norm(v1)
print(vmag)