In [3]:
import numpy as np
v1=np.array([1,2,3,4,5])
v2=np.array([6,7,3,1,-5])
# v3=np.array([15,23,3,4,5])
v3=v2-v1
print(v3)

[  5   5   0  -3 -10]


In [9]:
import numpy as np
v1=np.random.randn(2,5)
vtranspose=v1.T
print(vtranspose)
print("************************************************")
print(v1)
print("*******************************************")
print(np.transpose(v1))

[[-0.44608456 -1.32280017]
 [ 0.88971177 -0.89118678]
 [ 0.86467729  1.32163398]
 [-1.95563557  0.67759093]
 [ 0.10406958  0.9211154 ]]
************************************************
[[-0.44608456  0.88971177  0.86467729 -1.95563557  0.10406958]
 [-1.32280017 -0.89118678  1.32163398  0.67759093  0.9211154 ]]
*******************************************
[[-0.44608456 -1.32280017]
 [ 0.88971177 -0.89118678]
 [ 0.86467729  1.32163398]
 [-1.95563557  0.67759093]
 [ 0.10406958  0.9211154 ]]


In [24]:
#  types of matrics
import numpy as  np
# 1 eye matrics

# ««««««««««««««««««««««
# څومره خوند کوي چي دا سپیڅلي او پاکه پښتو په یو پروګرامینګ ژبه کي لیکم 
# ««««««««««««««««««««««
print(" دا دي د عیینت مترکس")
v1=np.eye(6,6)
print(v1)
#  this is the zeros vectors
print("*******************")
print(" zeros vector ")
print("*******************")
v2=np.zeros([6,4])
print(v2)
# ones vectors
print("*******************")
print(" ones vector ")
print("*******************")

v3=np.ones([4,4])
print(v3)



 دا دي د عیینت مترکس
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
*******************
 ones vector 
*******************
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
