from s ci p y . l i n a l g import hankel , t o e p l i t z
2 t = [ 1 , 2 , 3 , 4 ]
3 T = t o e p l i t z ( t )
4 H = h an kel ( t , r =[ 2 , 3 , 4 , 1] )


In [11]:
# # from  scipy.linalg import hankel,toeplitz
# import numpy as np
# t = [ 1 , 2 , 3 , 4 ]
# T=toeplitz(t)
# H = hankel( t , r =[ 2 , 3 , 4 , 1] )

# print(H)



In [12]:
import numpy as np
v1=np.array([2,3,3,4,5,6])
v2=np.array([[2],[3],[5],[6]])
print (v1)
print (v2)

[2 3 3 4 5 6]
[[2]
 [3]
 [5]
 [6]]


In [13]:
#  Transposing vectors
v1=np.array([1,2,3,4])
v2=v1.T
v3=v1.transpose

print(v3)

[1 2 3 4]
